<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .report-info {
            margin-bottom: 20px;
        }
        .report-info table {
            width: 100%;
            border-collapse: collapse;
        }
        .report-info td {
            padding: 5px;
        }
        .report-info td:first-child {
            font-weight: bold;
            width: 200px;
        }
        .sample-info, .test-info, .results {
            margin-bottom: 30px;
        }
        h2 {
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
            color: #444;
        }
        .results table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        .results th, .results td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        .results th {
            background-color: #f2f2f2;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: #777;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .signature {
            margin-top: 50px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
            text-align: right;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Laboratory Test Report</h1>
    </div>
    
    <div class="report-info">
        <table>
            <tr>
                <td>Report Number:</td>
                <td>{{ $report_number }}</td>
            </tr>
            <tr>
                <td>Report Title:</td>
                <td>{{ $title }}</td>
            </tr>
            <tr>
                <td>Generated Date:</td>
                <td>{{ $generated_at->format('F d, Y H:i') }}</td>
            </tr>
            <tr>
                <td>Generated By:</td>
                <td>{{ $user->name }}</td>
            </tr>
        </table>
    </div>
    
    <div class="sample-info">
        <h2>Sample Information</h2>
        <table>
            <tr>
                <td>Sample ID:</td>
                <td>{{ $test->sample->sample_id }}</td>
            </tr>
            <tr>
                <td>Client:</td>
                <td>{{ $test->sample->client_name }}</td>
            </tr>
            <tr>
                <td>Sample Type:</td>
                <td>{{ ucfirst(str_replace('_', ' ', $test->sample->sample_type)) }}</td>
            </tr>
            <tr>
                <td>Collection Date:</td>
                <td>{{ $test->sample->collection_date->format('F d, Y') }}</td>
            </tr>
            <tr>
                <td>Received Date:</td>
                <td>{{ $test->sample->received_date->format('F d, Y') }}</td>
            </tr>
            <tr>
                <td>Lab:</td>
                <td>{{ $test->lab->name }}</td>
            </tr>
        </table>
    </div>
    
    <div class="test-info">
        <h2>Test Information</h2>
        <table>
            <tr>
                <td>Test Type:</td>
                <td>{{ ucfirst(str_replace('_', ' ', $test->test_type)) }}</td>
            </tr>
            <tr>
                <td>Method:</td>
                <td>{{ $test->method }}</td>
            </tr>
            <tr>
                <td>Device Used:</td>
                <td>{{ $test->device ? $test->device->name . ' (' . $test->device->model . ')' : 'N/A' }}</td>
            </tr>
            <tr>
                <td>Started:</td>
                <td>{{ $test->started_at ? $test->started_at->format('F d, Y H:i') : 'N/A' }}</td>
            </tr>
            <tr>
                <td>Completed:</td>
                <td>{{ $test->completed_at ? $test->completed_at->format('F d, Y H:i') : 'N/A' }}</td>
            </tr>
            <tr>
                <td>Performed By:</td>
                <td>{{ $test->assignedUser ? $test->assignedUser->name : 'N/A' }}</td>
            </tr>
            <tr>
                <td>Approved By:</td>
                <td>{{ $test->approver ? $test->approver->name : 'N/A' }}</td>
            </tr>
        </table>
    </div>
    
    <div class="results">
        <h2>Test Results</h2>
        @if(is_array($test->results) && count($test->results) > 0)
            <table>
                <thead>
                    <tr>
                        <th>Parameter</th>
                        <th>Value</th>
                        <th>Unit</th>
                        <th>Reference Range</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($test->results as $parameter => $data)
                        <tr>
                            <td>{{ $parameter }}</td>
                            <td>{{ $data['value'] ?? 'N/A' }}</td>
                            <td>{{ $data['unit'] ?? 'N/A' }}</td>
                            <td>{{ $data['reference'] ?? 'N/A' }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <p>No results data available.</p>
        @endif
        
        @if($test->notes)
            <h3>Notes:</h3>
            <p>{{ $test->notes }}</p>
        @endif
    </div>
    
    <div class="signature">
        <p>Authorized Signature: _________________________</p>
        <p>Date: _________________________</p>
    </div>
    
    <div class="footer">
        <p>This report relates only to the sample(s) tested and shall not be reproduced except in full, without written approval of the laboratory.</p>
        <p>End of Report</p>
    </div>
</body>
</html>
