@extends("layouts.app")

@section("title", "Reports")

@section("content")
<div class="container-fluid">
    <h1 class="h3 mb-2 text-gray-800">Reports</h1>
    <p class="mb-4">View and download generated test reports.</p>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Report List</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Report ID</th>
                            <th>Title</th>
                            <th>Test ID</th>
                            <th>Sample ID</th>
                            <th>Generated By</th>
                            <th>Generated At</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($reports as $report)
                            <tr>
                                <td>{{ $report->id }}</td>
                                <td>{{ $report->title }}</td>
                                <td><a href="{{ route("tests.show", $report->test) }}">{{ $report->test->id }}</a></td>
                                <td><a href="{{ route("samples.show", $report->test->sample) }}">{{ $report->test->sample->sample_id }}</a></td>
                                <td>{{ $report->generator->name }}</td>
                                <td>{{ $report->created_at->format("Y-m-d H:i:s") }}</td>
                                <td>
                                    <a href="{{ route("reports.show", $report) }}" class="btn btn-info btn-sm">View Details</a>
                                    <a href="{{ route("reports.download", $report) }}" class="btn btn-success btn-sm">Download PDF</a>
                                    @can("manage reports")
                                    <form action="{{ route("reports.destroy", $report) }}" method="POST" class="d-inline" onsubmit="return confirm("Are you sure you want to delete this report?");">
                                        @csrf
                                        @method("DELETE")
                                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                    </form>
                                    @endcan
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="7" class="text-center">No reports found.</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

