@extends("layouts.app")

@section("title", "Report Details: #" . $report->id)

@section("content")
<div class="container-fluid">
    <h1 class="h3 mb-2 text-gray-800">Report Details: #{{ $report->id }} - {{ $report->title }}</h1>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Report Information</h6>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <p><strong>Report ID:</strong> {{ $report->id }}</p>
                    <p><strong>Title:</strong> {{ $report->title }}</p>
                    <p><strong>Test ID:</strong> <a href="{{ route("tests.show", $report->test) }}">{{ $report->test->id }}</a></p>
                    <p><strong>Sample ID:</strong> <a href="{{ route("samples.show", $report->test->sample) }}">{{ $report->test->sample->sample_id }}</a></p>
                    <p><strong>Sample Type:</strong> {{ Str::title(str_replace("_", " ", $report->test->sample->sample_type)) }}</p>
                </div>
                <div class="col-md-6">
                    <p><strong>Generated By:</strong> <a href="{{ route("users.show", $report->generator) }}">{{ $report->generator->name }}</a></p>
                    <p><strong>Generated At:</strong> {{ $report->created_at->format("Y-m-d H:i:s") }}</p>
                    <p><strong>Lab:</strong> <a href="{{ route("labs.show", $report->test->sample->lab) }}">{{ $report->test->sample->lab->name }}</a></p>
                </div>
            </div>
            <hr>
            <a href="{{ route("reports.index") }}" class="btn btn-secondary">Back to List</a>
            <a href="{{ route("reports.download", $report) }}" class="btn btn-success">Download PDF</a>
        </div>
    </div>

    <!-- Test Details Summary -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Test Summary</h6>
        </div>
        <div class="card-body">
            <p><strong>Test Type:</strong> {{ Str::title(str_replace("_", " ", $report->test->test_type)) }}</p>
            <p><strong>Method (ASTM):</strong> {{ $report->test->method }}</p>
            <p><strong>Status:</strong> <span class="{{ $report->test->status_badge }}">{{ Str::title(str_replace("_", " ", $report->test->status)) }}</span></p>
            <p><strong>Completed At:</strong> {{ $report->test->completed_at ? $report->test->completed_at->format("Y-m-d H:i:s") : "N/A" }}</p>
            <p><strong>Approved By:</strong> {{ $report->test->approver?->name ?? "N/A" }}</p>
            <p><strong>Results:</strong></p>
            @if($report->test->results)
                <pre class="bg-light p-3 rounded"><code>{{ json_encode($report->test->results, JSON_PRETTY_PRINT) }}</code></pre>
            @else
                <p>No results recorded.</p>
            @endif
        </div>
    </div>

</div>
@endsection

